let stats = {
    hash: 'f029cd07cb600feed88d',
    version: '5.64.0',
    time: 398,
    builtAt: 1636719292763,
    publicPath: 'auto',
    outputPath: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\dist',
    assetsByChunkName: { entry1: ['entry1.js'], entry2: ['entry2.js'] },
    assets: [
        {
            type: 'asset',
            name: 'entry2.js',
            size: 1633,
            emitted: false,
            comparedForEmit: true,
            cached: false,
            info: [Object],
            chunkNames: [Array],
            chunkIdHints: [],
            auxiliaryChunkNames: [],
            auxiliaryChunkIdHints: [],
            filteredRelated: undefined,
            related: {},
            chunks: [Array],
            auxiliaryChunks: [],
            isOverSizeLimit: false
        },
        {
            type: 'asset',
            name: 'entry1.js',
            size: 1632,
            emitted: false,
            comparedForEmit: true,
            cached: false,
            info: [Object],
            chunkNames: [Array],
            chunkIdHints: [],
            auxiliaryChunkNames: [],
            auxiliaryChunkIdHints: [],
            filteredRelated: undefined,
            related: {},
            chunks: [Array],
            auxiliaryChunks: [],
            isOverSizeLimit: false
        }
    ],
    filteredAssets: undefined,
    chunks: [
        {
            rendered: true,
            initial: true,
            entry: true,
            recorded: false,
            reason: undefined,
            size: 86,
            sizes: [Object: null prototype],
            names: [Array],
            idHints: [],
            runtime: [Array],
            files: [Array],
            auxiliaryFiles: [],
            hash: '1ac2c1997651cd1d13c0',
            childrenByOrder: [Object: null prototype] {},
        id: 'entry1',
        siblings: [],
        parents: [],
        children: [],
        origins: [Array]
    },
    {
        rendered: true,
        initial: true,
        entry: true,
        recorded: false,
        reason: undefined,
        size: 87,
        sizes: [Object: null prototype],
        names: [Array],
        idHints: [],
        runtime: [Array],
        files: [Array],
        auxiliaryFiles: [],
        hash: '643d91b04008eb6c9565',
        childrenByOrder: [Object: null prototype] { },
    id: 'entry2',
    siblings: [],
    parents: [],
    children: [],
    origins: [Array]
    }
  ],
modules: [
    {
        type: 'module',
        moduleType: 'javascript/auto',
        layer: null,
        size: 61,
        sizes: [Object],
        built: true,
        codeGenerated: true,
        buildTimeExecuted: false,
        cached: false,
        identifier: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\entry1.js',
        name: './src/entry1.js',
        nameForCondition: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\entry1.js',
        index: 0,
        preOrderIndex: 0,
        index2: 1,
        postOrderIndex: 1,
        cacheable: true,
        optional: false,
        orphan: false,
        dependent: undefined,
        issuer: null,
        issuerName: null,
        issuerPath: null,
        failed: false,
        errors: 0,
        warnings: 0,
        id: './src/entry1.js',
        issuerId: null,
        chunks: [Array],
        assets: [],
        reasons: [Array],
        filteredReasons: undefined,
        usedExports: null,
        providedExports: null,
        optimizationBailout: [],
        depth: 0
    },
    {
        type: 'module',
        moduleType: 'javascript/auto',
        layer: null,
        size: 62,
        sizes: [Object],
        built: true,
        codeGenerated: true,
        buildTimeExecuted: false,
        cached: false,
        identifier: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\entry2.js',
        name: './src/entry2.js',
        nameForCondition: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\entry2.js',
        index: 2,
        preOrderIndex: 2,
        index2: 2,
        postOrderIndex: 2,
        cacheable: true,
        optional: false,
        orphan: false,
        dependent: undefined,
        issuer: null,
        issuerName: null,
        issuerPath: null,
        failed: false,
        errors: 0,
        warnings: 0,
        id: './src/entry2.js',
        issuerId: null,
        chunks: [Array],
        assets: [],
        reasons: [Array],
        filteredReasons: undefined,
        usedExports: null,
        providedExports: null,
        optimizationBailout: [],
        depth: 0
    },
    {
        type: 'module',
        moduleType: 'javascript/auto',
        layer: null,
        size: 25,
        sizes: [Object],
        built: true,
        codeGenerated: true,
        buildTimeExecuted: false,
        cached: false,
        identifier: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\title.js',
        name: './src/title.js',
        nameForCondition: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\title.js',
        index: 1,
        preOrderIndex: 1,
        index2: 0,
        postOrderIndex: 0,
        cacheable: true,
        optional: false,
        orphan: false,
        dependent: undefined,
        issuer: 'C:\\aproject\\zhufengwebpack202111\\4.flow\\src\\entry1.js',
        issuerName: './src/entry1.js',
        issuerPath: [Array],
        failed: false,
        errors: 0,
        warnings: 0,
        id: './src/title.js',
        issuerId: './src/entry1.js',
        chunks: [Array],
        assets: [],
        reasons: [Array],
        filteredReasons: undefined,
        usedExports: null,
        providedExports: null,
        optimizationBailout: [Array],
        depth: 1
    }
],
    filteredModules: undefined,
        entrypoints: [Object: null prototype] {
    entry1: {
        name: 'entry1',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1632,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    },
    entry2: {
        name: 'entry2',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1633,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    }
},
namedChunkGroups: [Object: null prototype] {
    entry1: {
        name: 'entry1',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1632,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    },
    entry2: {
        name: 'entry2',
            chunks: [Array],
                assets: [Array],
                    filteredAssets: 0,
                        assetsSize: 1633,
                            auxiliaryAssets: [],
                                filteredAuxiliaryAssets: 0,
                                    auxiliaryAssetsSize: 0,
                                        children: [Object: null prototype] { },
        childAssets: [Object: null prototype] { },
        isOverSizeLimit: false
    }
},
errors: [],
    errorsCount: 0,
        warnings: [],
            warningsCount: 0,
                children: []
}